### PR TITLE
2020 - 2021 Update Part 1

### PR DESCRIPTION
**Pull request by Suriya-2002**
## Proposed Changes

- Added team 20-21 page in navigation menu drop-down
- Updated team 20-21 members in testimonials section of home page
- Added team 20-21 page with secretaries and joint secretaries

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Suriya-2002 I've fixed a few things in your PR. You can check the commit history for changes. Few points to note:

- Please use 245*245 images for all images in `public/images/team_2021/`.
- Don't duplicate images. We can use images in the previous year folders.
- FACE executives are missing on the team page.
- Mentors are missing on the main page (Except FACE). Maybe keep mentors as a separate slider instead of merging with office bearers as they aren't?
- `public/images/team_2021/tarun.jpg` has whitespace. Should be changed to a full-frame picture.
- `public/images/team_2021/sneha.png` Sneha is too far in the image.
- `public/images/team_2021/akkina.jpg` face is hardly visible.
- Stick to one image format `.jpg` instead of mixing and matching `.png` and `.jpeg`.
- Use compressed images ([Tool](https://imagecompressor.com/)).

**Comment by Suriya-2002** [comment]
@sathian-icd will take care of adding FACE executives to team page. I shall inform all these instructions to him. 
I will complete the remaining tasks and add-in commits to this PR, as soon as I get inputs.

**Comment by aravindvnair99** [comment]
> @sathian-icd will take care of adding FACE executives to team page. I shall inform all these instructions to him.
> I will complete the remaining tasks and add-in commits to this PR, as soon as I get inputs.

Cool. By the way @Suriya-2002, you are part of the organization. Next time, send the PR from within the repo as the checks won't run completely otherwise.

**Comment by Suriya-2002** [comment]
> > @sathian-icd will take care of adding FACE executives to team page. I shall inform all these instructions to him.
> > I will complete the remaining tasks and add-in commits to this PR, as soon as I get inputs.
> 
> Cool. By the way @Suriya-2002, you are part of the organization. Next time, send the PR from within the repo as the checks won't run completely otherwise.

Oh, is it! Alright. Will do it next time.

**Comment by Suriya-2002** [comment]
Had done all changes except for the second carousel, and the FACE executive members will be added by @sathian-icd once my PR is merged.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Suriya-2002 I've put a placeholder for mentors' slider. You can fill it up and then this PR can be merged. Pull before making changes.

**Review by aravindvnair99 — COMMENTED** [review]
@Suriya-2002 So far looks good.

One thing did strike me now though. Usually, the mentors don't change often. I felt we should also add all of them to team pages for every year as for example, Manju Ma'am was the mentor for FACE from 2018 to 2020 until Rajakumar Sir took over in 2021.

But right now, all the team pages only consist of office bearers and executives. @ry05 @adityadu-18 @newb-dev-1008 What say?

**Comment by newb-dev-1008** [comment]
@aravindvnair99 sounds good, the mentors can probably be added to the top of their corresponding team pages under a seperate "Mentors" div. That div can contain mentors not just for FACE, but for all sister clubs (as the CSI mentor has also changed and there are frequent changes in mentors inbound).

**Comment by ry05** [comment]
Adding the mentors is a really good idea! I would also propose that you could get in the research interests of the mentors as their bio. Probably you could get this of the official ASE-B page.

**Comment by aravindvnair99** [comment]
@Suriya-2002 Any updates?

**Comment by Suriya-2002** [comment]
We weren't able to get the LinkedIn profile for Manju Venugopalan ma'am.

**Comment by aravindvnair99** [comment]
> We weren't able to get the LinkedIn profile for Manju Venugopalan ma'am.

@Suriya-2002 This is her profile: https://linkedin.com/in/manju-sreekumar-5b634578

I don't think she uses it though. Apart from me, she has only 5 other connections. So, we can skip that.

**Review by aravindvnair99 — DISMISSED** [review]

**Review by aravindvnair99 — APPROVED** [review]

**Comment by aravindvnair99** [comment]
@Suriya-2002 I've merged your contributions after fixing few things and deployed. Only executives for 2020 - 2021 is left which you mentioned @sathian-icd will be doing in https://github.com/FACE-Amrita-Bengaluru/Website/pull/219#issuecomment-813344104. You can inform him accordingly. Title the PR `2020 - 2021 Update Part 2` and do it from within this repo. Make sure to be in sync with this repo.

**Pull request merged**
