### PR TITLE
2020 - 2021 Update Part 2

### LINKED ISSUE #222: 2020 - 2021 Update
- [x] Add 2020 - 2021 to the menu
- [x] Create 2020 - 2021 page
- [x] Update the main page with the 2020 - 2021 team
- [x] Add mentors for all years
- [x] Update dependencies
- [x] Switch to npm 7
- [x] Fix all images
- [x] Fix `&amp;`
- [x] Update ESLint
- [x] Switch dependencies to CDN
- [x] Fix copyright year
- [x] Update CI / CD
- [x] Update docs
- [x] Update sitemap
- [x] Refactor

### PR DESCRIPTION
**Pull request by sathian-icd**
Fixes #222

## Proposed Changes

-Executives list updated
-Images are in 245x245 px and compressed

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@sathian-icd Some of the pictures are not clear / not professional looking. Please recheck. Also, some of them have unnecessary objects in the image. It should be just the face directly. I noticed you changed a few pictures as well where the previous one looked much better, and the newer image is grainy. Better to revert that. Undo the commit and edit accordingly. Also, stick to the naming convention for the file names. Let's keep things consistent.

**Comment by sathian-icd** [comment]
> @sathian-icd Some of the pictures are not clear / not professional looking. Please recheck. Also, some of them have unnecessary objects in the image. It should be just the face directly. I noticed you changed a few pictures as well where the previous one looked much better, and the newer image is grainy. Better to revert that. Undo the commit and edit accordingly. Also, stick to the naming convention for the file names. Let's keep things consistent.

so, I made the changes you asked for. 
I reverted the grainy new images to the old clear ones.
I've also updated new images for the grainy ones.
I also followed the old naming convention that you asked

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@sathian-icd The following images have to be changed:
- public/images/team_2021/Gandheesh.jpg (I think that's some girl's hair in front of him)
- public/images/team_2021/Praanesh.jpg (Not clear)
- public/images/team_2021/Sukha.jpg (Looks like the image is horizontally squashed. Happens when the image is resized irrespective of aspect ratio instead of cropping)

**Comment by sathian-icd** [comment]
let me know if there are any other changes🙂

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Also,

- public/images/team_2021/pranav.jpg (Is there a better picture where he's the subject than have other objects)
- public/images/team_2021/harsha.jpg (blurry)

**Comment by sathian-icd** [comment]
I will make these changes as soon as I get these images.

**Comment by sathian-icd** [comment]
I've changed the images you mentioned. @aravindvnair99 
also, yash mentioned that you want me to create a fresh pull request

**Comment by aravindvnair99** [comment]
@sathian-icd No fresh PR isn't required. I'll review this PR shortly.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@sathian-icd Just reviewed your PR. Everything looks good except `public/images/team_2021/sukha.png` where the image looks squashed horizontally.

**Comment by sathian-icd** [comment]
@aravindvnair99 Just updated that. Let me know if there is anything else.

**Review by aravindvnair99 — APPROVED** [review]

**Pull request merged**
